### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by biozzq** [ekg/wfmash#113]
Hi，
I have installed wfmash by using anaconda, however, it give me the following information when no option is used. I think my installation still has some unknown problems. Thank you in advance.  
```
wfmash 
  wfmash [target] [queries...] {OPTIONS}

    wfmash: base-accurate alignments using mashmap2 and the wavefront algorithm

  OPTIONS:

      -h, --help                        display this help menu
      -t[N], --threads=[N]              use this many threads during parallel
                                        steps
      target                            alignment target or reference sequence
                                        file
      -L[targets],
      --target-file-list=[targets]      alignment target file list
      queries...                        query sequences
      -Q[queries],
      --query-file-list=[queries]       alignment query file list
      -s[N], --segment-length=[N]       segment length for mapping (1k = 1K =
                                        1000, 1m = 1M = 10^6, 1g = 1G = 10^9)
                                        [default: 5000]
      -l[N], --block-length-min=[N]     keep mappings with at least this block
                                        length (1k = 1K = 1000, 1m = 1M = 10^6,
                                        1g = 1G = 10^9) [default:
                                        3*segment-length]
      -k[N], --kmer=[N]                 kmer size <= 16 [default: 16]
      -N, --no-split                    disable splitting of input sequences
                                        during mapping [enabled by default]
      -p[%], --map-pct-id=[%]           use this percent identity in the mashmap
                                        step [default: 95]
      -K, --keep-low-map-id             keep mappings with estimated identity
                                        below --map-pct-id=%
      -O, --keep-low-align-id           keep alignments with gap-compressed
                                        identity below --map-pct-id=%
      -f, --no-filter                   disable mapping filtering
      -n[N],
      --num-mappings-for-segment=[N]    number of mappings to retain for each
                                        segment [default: 1]
Illegal instruction (core dumped)
```
Sincerely,
Zheng zhuqing

**Comment by smarco** [comment]
Hi,

It seems to me that the machine/processor you are using is non-compliant with the instructions/ISA for which wfmash was compiled for the anaconda distribution. Please, can you let us know the processor and model you are using for your executions?

Thanks,

**Comment by biozzq** [comment]
Hi,

Sorry for the late reply. All my executions were submitted through bsub. I found wfmash can run smoothly on the login node. When I submit the command to the compute node, the program gives me the above error. After using other nodes, the program can work on the demo data (small test data) now, however, when i using my real data (three genomes with 2.7G), wfmash exited with following information.

```
wfmash -X -s 100000 -l 300000 -p 98 -n 3 -k 16 -t 4 graph.fa graph.fa
[wfmash::map] Reference = [graph.fa]
[wfmash::map] Query = [graph.fa]
[wfmash::map] Kmer size = 16
[wfmash::map] Window size = 256
[wfmash::map] Segment length = 100000 (read split allowed)
[wfmash::map] Block length min = 300000
[wfmash::map] Alphabet = DNA
[wfmash::map] Percentage identity threshold = 98%
[wfmash::map] Mapping output file = 03.Graph_genome/wfmash-YYTv9Y
[wfmash::map] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
[wfmash::map] Execution threads  = 4
[wfmash::skch::Sketch::build] minimizers picked from reference = 60834448
[wfmash::skch::Sketch::index] unique minimizers = 8207939
[wfmash::skch::Sketch::computeFreqHist] Frequency histogram of minimizers = (1, 468608) ... (596213, 1)
[wfmash::skch::Sketch::computeFreqHist] With threshold 0.001%, ignore minimizers occurring >= 8959 times during lookup.
[wfmash::map] time spent computing the reference index: 100.513 sec
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted

```
Do you have any suggestions, thanks in advance.

Besy wishes;
Zheng zhuqing

**Comment by AndreaGuarracino** [comment]
Hi @biozzq,

may I ask you to execute `cat -A graph.fa | head -n 5` and share the output?

**Comment by biozzq** [comment]
Dear @AndreaGuarracino 

My sequence data is simply placed on a single line. Since it's very long, I only share a part of them here,

```
>h1tg000001l$
TAACTTTAACTTTAACTGTTAACTTTAACTTTAAACTTTAACTTTAACTTTAACTTTGAACTTTAACTTTAACTTTAACGTTAACTTTAACTGTACGTAACTGTAACTTAACTTTAACTTTAACTTTAACTTTAACTTTAACTTAACTTTAACGTTTA......$
>h1tg000002l$
CTAACCCTAACCCTAACCCTATCCCTAACCCTAACCCTAGGAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCTAACCCTAACCCTAT......$
>h1tg000003l$
CCTCCCAGGCGAGAAACGCCGGAGGCCACCCCTCCCAGTTGCCCTCGGGTGCGGGTGCTGTGTGCCACGTGCCACGTGCGGTGGGCTACGCCCGGGTGGGGGGGGGGGGGGCGACGGCGGAGTTCCTGCCGCTGCCGCCTGTGCTGGCCGGCGTGCCC......$
>h1tg000004l$
AGAAGATGACCTGCAGCGGCACAGACGCCAGCAAAGGCAGAAGCCATCCCGTCTTGGGTGAGGTGCCCGAGACGCGCCTCTCTAACCCAGTCCCGCCCTGTCCTTGGAGAAGCGGGCGGTGTCTGGAAAAGCCTGACCAGGTGTCTTTCCTCGGTGGG.....$
```

Best,
Zheng zhuqing

**Comment by AndreaGuarracino** [comment]
Thank you @biozzq,
I wanted to confirm that your problem is different from [this one](https://github.com/ekg/wfmash/issues/110#issuecomment-1013447287) in #110. It seems so, as I don't see any `^M` at the end of your sequences.

Are you able to execute `wfmash` with your real data (three genomes with 2.7G) on another computer?

**Comment by lsoldini** [comment]
Hi, 

I have the same problem as initially stated by this issue thread. I've installed `wfmash` (last version) using `conda install -c bioconda wfmash`, but the program stops working due to `illegal instruction (core dumped)` :

1. When I try to access wfmash help with `wfmash --help`, I get `Illegal instruction (core dumped)` (the options of the help are not even printed, it goes straight to this error). 
2. If I try to run `wfmash -X -i full_genome.fasta -s 5000 -p 90`, I get the same error (i.e., here the full_genome.fasta corresponds to two genomes of approximately 200 Mb from the same species but different haplotypes, and the folder also included a `full_genome.fasta.fai` file genereated with `samtools faidx` as suggested elsewhere).

Do you have any idea why this may happen ? 

I should also mention that I am trying `wfmash` because I had problems in the `pggb` pipeline. Indeed, I was initially trying that pipeline to build a variationg graph from two insect genomes of app. 200 Mb (two genomes from the same species but different populations, in particular these include large structural variants). I have tried with different installations (namely, `conda` and `singularity` - i.e., I am working on a HPC cluster with Slurm), but it kept failing. 

- For the conda installation (version 0.3.0 updated the 02.04.22), it was `wfmash` failing due to `Command terminated by signal 4`. 
- For the singularity installation (last image as of 04.04.22), it was the the wfmash and seqwish steps seemed to work just fine, but the error occured in the smoothxg part `[smoothxg::main] prepping graph for smoothing
Command terminated by signal 4`. I also tried to install `smoothx` with `conda` and try manually with the `.seqwish.gaf` output, but this was not working due to an error that stopped the program (I do not recall the error message but I can re-run it if necessary).

Overall, the fact that I could not use the `pggb` pipeline led me to try each component individually (i.e., `wfmash`, `seqwish`, and `smoothxg`). Since I had that many problems with different installations, I thought that this may be linked to some software missing on the HPC cluster I am working, and I thought maybe this thread was approriate, but my apologies if I should have written this on the `pggb` github or elsewhere.

Please let me know if I should give any other information.

Thanks in advance for your time reading this. 

Best, 
Luca

**Comment by AndreaGuarracino** [comment]
Hi @lsoldini , thank you for your report.

There seem to be a number of compilation issues preventing PGGB tools from working properly.

The conda installation of `wfmash` and `smoothxg` may fail due to too specific flags during its compilation. I will update their conda versions soon, to have new updates in their compilation way. Then it would be nice if you could try them again.

Instead, the singularity installation should already be up-to-date, so such an error is quite strange. How did you install `pggb` with singularity? Did you follow the README?

**Comment by lsoldini** [comment]
Hi @AndreaGuarracino, thank you for your quick answer. 

I will then try again when new conda versions are available and give feedback here. 

To install `pggb` with singularity, I followed the README:
`singularity pull docker://ghcr.io/pangenome/pggb:latest`
`git clone --recursive https://github.com/pangenome/pggb.git`

Using the singularity installation was clearly way better than the conda installation, and it allowed me to go further in the process, although I did not manage to obtain the smoothed .gfa. 

I have pasted below the last lines of the error message I have:
```
[smoothxg::main] loading graph
[smoothxg::main] prepping graph for smoothing
Command terminated by signal 4
smoothxg -t 20 -T 20 -g /full_genome/test101/full_genome.fasta.736e971.7bdde5a.seqwish.gfa -w 4000 -X 100 -I .9000 -R 0 -j 0 -e 0 -l 20
00 -P 1,19,39,3,81,1 -O 0.03 -Y 200 -d 0 -D 0 -Q Consensus_ -V -o /full_genome/test101/full_genome.fasta.736e971.7bdde5a.d49683e.smooth
.gfa
0.00s user 0.08s system 21% cpu 0.43s total 25256Kb max memory
```

I may have done something wrong at another moment. Here is the command I used with singularity: `singularity run -B ~/scratch/pggb/full_genome:/full_genome ~/work/pggb_latest.sif "pggb -i /full_genome/full_genome.fasta -p 90 -s 5000
 -G 2000 -n 2 -v -V 'FSel#:#:' -o /full_genome/test101 -t 20 -T 20"`

Also, the genome I am using has 27 nicely defined scaffolds but also many contigs (500+). Maybe this could be an issue for the `smoothxg` part?

I've tried to read most of issues on Github, either for `pggb`, `wfmash`, `smoothxg`, etc. but could not find what I am doing wrong. 

Thank you, 
Luca

**Comment by lsoldini** [comment]
Hi @AndreaGuarracino, thank you for your answer and for working on this new docker image. 

I've dowloaded the new image (07.04.22), and the previous error occuring in `smoothxg` preventing graph prepping is solved!

On the other hand, the command I used (1) was still interrupted before finishing. However, the message error (2) seems to be related to the way I formated the first line of my fasta sequences (i.e., I followed the [PanSN-spec](https://github.com/pangenome/PanSN-spec) as suggested, but I must have done it wrong). 

Thank you very much for your fast answer and solving of the issue! 

(1) `singularity run -B ~/scratch/pggb/full_genome:/full_genome ~/work/pggb_latest.sif "pggb -i /full_genome/full_genome.fasta -p 90 -s 5000 -G 2000 -n 2 -v -V 'FSel#:#:' -o /full_genome/test101 -t 20 -T 20"`

(2) `[vg::deconstruct] making VCF with reference=FSel# and delim=#`
`Error [vg deconstruct]: No specified reference path or prefix found in graph`
`Command exited with non-zero status 1`

**Comment by AndreaGuarracino** [comment]
Instead of `-V 'FSel#:#:'`, specify `-V FSel:#`.

If you can share your path names or your `/full_genome/full_genome.fasta.fai` file, I can take a closer look.

**Comment by lsoldini** [comment]
I'll try to give what seems key for understanding because the `/full_genome/full_genome.fasta.fai` is quite long (1000+ entries), although I'll still paste some of it bellow.

I am working on a species (FSel, an ant species) existing in two "populations" and we have a genome for each population (let's say 1 and 2). There are 27 scaffolds and 500+ contigs. 

Following [PanSN-spec](https://github.com/pangenome/PanSN-spec), I thought using Fsel#1#scaff_or_contig_name (and same with #2) would match. 

Should I try with `-V Fsel:#` or do you think something more should be changed ?

Here are the few lines of the `/full_genome/full_genome.fasta.fai`

```
FSel#1#scf1     15335615        13      60      61
FSel#1#scf4     14177260        15591235        60      61
FSel#1#scf3     14011714        30004796        60      61
FSel#1#scf10    13402687        44250053        60      61
FSel#1#scf8     12641717        57876132        60      61
FSel#1#scf7     12339748        70728558        60      61
FSel#1#scf5     12127983        83273982        60      61
```

**Comment by AndreaGuarracino** [comment]
Yes, a few path names are enough.

I would not distinguish the two populations by using the `haplotype_id` (second field in PanSN-spec), as it is for handling different ploidies or contig groups of the same sample, at least in general.

If I understand correctly, there are two samples, both haploid, and you want to call variants with respect to one and the other. I would rename samples in something like `Fsel_pop1#1#scaff_or_contig_name` and `Fsel_pop2#1#scaff_or_contig_name`, and specify `-V Fsel_pop1:#,Fsel_pop2:#` in `pggb` to call variants with respect to both references.
